### ISSUE TITLE
Driver needs to be changed to employee

### ISSUE THREAD

**Issue by Aaidenplays** [learn-co-curriculum/phase-0-intro-to-js-2-objects-lab#3] opened 2021-08-28 19:35 UTC
Thanks for raising this issue! Future learners thank you for your diligence. In
order to help the curriculum team address the problem, please use this template
to submit your feedback. We'll work on addressing the issue as soon as we can.

Please fill out as much of the information below as you can (it's ok if you
don't fill out every section). The more context we have, the easier it will be
to fix your issue!

_**Note**: you should only raise issues related to the contents of this lesson.
If you have questions about your code or need help troubleshooting, reach out to
an instructor/your peers._

---

both the tests and the instructions refer to the creation of driver objects. However, the code needs to create new employee objects. I think this is throwing some students for a loop. 

## Link to Canvas
unfortunately, I do not have access to Canvas material.

> Add a link to the assignment in Canvas here.

## What should be changed?

> Suggest your change here. Let us know what section or line of the Readme needs
> to be updated, and any proposed corrections. Include the line number(s) if
> possible.

## Additional context

> Add any other context about the problem here.

**Comment by lizbur10** [comment] 2021-08-30 12:17
Hi @Aaidenplays ! I've searched through the code and not found any reference to driver. Is it possible that it was a different lab?

**Comment by lizbur10** [comment] 2021-09-02 13:37
Hi again @Aaidenplays ! I'm going to go ahead and close this issue. If you can find where the problem is, please re-post! 💙

**Closed by lizbur10** 2021-09-02 13:37 UTC
Labels: documentation
